name: Markdown linting

# When this workflow triggers
on:
  push:
  workflow_dispatch:

# Job definition
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: avto-dev/markdown-lint@v1
      with:
        config: '.markdownlint.json'
        agrs: '*.md **/*.md'